name: "FlywayWorkflow"
 
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'SQL/**'

jobs:
  Migrate:
    if: github.event.pull_request.merged == true
    name: RunMigration
    runs-on: ubuntu-20.04         
    steps:
      - name: RunMigration
        uses: actions/checkout@v3.0.0
      - run: wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.7.1/flyway-commandline-10.7.1-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-10.7.1/flyway /usr/local/bin
      - run: flyway -user="${{ secrets.DB_USERNAME }}" -password="${{ secrets.DB_PASSWORD }}" -url="${{ secrets.DB_URL }}" info
      - run: flyway -user="${{ secrets.DB_USERNAME }}" -password="${{ secrets.DB_PASSWORD }}" -url="${{ secrets.DB_URL }}" migrate